branches: master
cache: bundler
gemfile:
  - gemfiles/rails_4_0.gemfile
  - gemfiles/rails_4_1.gemfile
  - gemfiles/rails_4_2.gemfile
language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
rvm:
  - "2.0"
  - "2.1"
  - "2.2"
  - ruby-head
sudo: false
